/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -i public/plus.glb -o Model.jsx 
Files: public/plus.glb [8.44KB] > C:\Users\Fedor\Documents\work\twisting-plus\plus-transformed.glb [1.86KB] (78%)
Author: wextra052 (https://sketchfab.com/wextra052)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plus-sign-low-poly-c32ec7169bb7451a930b189dfbd57bb7
Title: Plus sign Low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
   const { nodes, materials } = useGLTF('/plus-transformed.glb')
   return (
      <group {...props} dispose={null} >
         <mesh geometry={nodes.pCube94_plus_0.geometry} scale={0.01} />
      </group>
   )
}

useGLTF.preload('/plus-transformed.glb')
